$(function(){
    $(".itm1").click(function(){
        $(".panel1").slideToggle("slow");
        $(".xs1").toggle();
        $(".xs2").toggle();
      });});
$(function(){
    $(".itm2").click(function(){
        $(".panel2").slideToggle("slow");
        $(".xs1").toggle();
        $(".xs2").toggle();
      });});
$(function(){
    $(".itm3").click(function(){
        $(".panel3").slideToggle("slow");
        $(".xs1").toggle();
        $(".xs2").toggle();
      });});
$(function(){
    $(".itm4").click(function(){
        $(".panel4").slideToggle("slow");
        $(".xs1").toggle();
        $(".xs2").toggle();
      });});
$(function(){
    $(".itm5").click(function(){
        $(".panel5").slideToggle("slow");
        $(".xs1").toggle();
        $(".xs2").toggle();
      });});